### ISSUE TITLE
Not able to delete an account

### ISSUE THREAD

**Issue by sagarhani** [fsmk/fsmk-discuss#1]
![fsmk-discuss](https://cloud.githubusercontent.com/assets/6933389/10904120/991f7fa0-8236-11e5-92cc-58ae3f8798f7.png)

`Delete My Account` button is disabled. How one can delete an account ?

I checked the [FAQ](https://discuss.fsmk.org/faq), [terms of service](https://discuss.fsmk.org/tos), etc.
I didn't find any guide to delete an account.

**Comment by shijiltv** [comment]
Hey it is possible. There are bunch of variables that I have to configure. Can you please share the detail shown with  tooltip when you hover ?

**Comment by sagarhani** [comment]
![fsmk-discuss-on-hover](https://cloud.githubusercontent.com/assets/6933389/10915987/439d5dba-827f-11e5-996d-3c6168521b97.png)

On hover I see :no_entry_sign: symbol.

**Comment by shijiltv** [comment]
I think you should be able to delete your account now. By default discourse wont allow you to delete account whose first post is older than (60) days. I have set (0) now. Check it..

**Comment by sagarhani** [comment]
![fsmk-discuss-update](https://cloud.githubusercontent.com/assets/6933389/10939744/e66eba2a-8329-11e5-8633-2d191e6a9a6d.png)
It is still showing :no_entry_sign: symbol.

![stat](https://cloud.githubusercontent.com/assets/6933389/10939763/00aeaa4e-832a-11e5-95e0-5be7c208e577.png)

I joined discourse yesterday. I have not made any post. 
Also, https://discuss.fsmk.org itself is not even 30 days old. So, Anyone should be able to delete his/her account.

**Comment by shijiltv** [comment]
I could not find a right solution for this. However I found this "Remember the rule -- 1 post or less. There might be a time limit in days as well." from post https://meta.discourse.org/t/leaving-a-forum-deleting-your-own-account/10732. If you want to delete your account immediately I can do it from admin account. Would appreciate if you can help me to find right solution.

**Comment by shijiltv** [comment]
Can you check it now ?

**Comment by sagarhani** [comment]
It is still same.

**Comment by sagarhani** [comment]
Ok

**Comment by sagarhani** [comment]
Okay, my account got delted now. Did you do that from admin account ?

**Comment by shijiltv** [comment]
It was automatically deleted by system. Context given as "Automatically deleted as abandoned, unactivated account"

**Comment by sagarhani** [comment]
:+1:
